### ISSUE TITLE
how to install with hybrid and ... 

### ISSUE THREAD

**Issue by chuckingit** [erikflowers/shoelace-theme#1]
Hi - i tried installing shoelace and got fatal errors ... i wasn't sure if i had to rename theme directories (e.g., from shoelace-theme-master to shoelace, or hybrid-base-master to hybrid-core) and various attempts all bombed ... but back to original fatal errors on theme activation ... these errors complained about functions.php in shoelace circa line 32 that has reference to path and file that is missing from my setup ... 

`e.g., /* Load the core theme framework. */
require_once( trailingslashit( get_template_directory() ) . 'library/hybrid.php' );`

there is no hybrid.php in the shoelace library subfolder ... nor do i see any hybrid.php in any of the hybrid base folders ... 

accordingly, what are the steps required to install shoelace -> e.g., "download this hybid core here, rename folder on server in themes to this, upload shoelace, modify functions.php file to point to this path for hybrid integration, yada yada ..."

thanks in advance for sharing ... had high hopes in that i love both ThemeHybrid and Bootstrap 3 thus was bummed at my failure to get it going ...

cordially, chuck scott 

ps - is shoelace BuddyPress and/or bbPress friendly ..??..

**Comment by chuckingit** [comment]
okay - i think i'm answering my own questions in that i did some digging at ThemeHybrid.com and got shoelace to work (or so i think) ... so here are my success steps ... 

a) download ThemeHybrid Core ... https://github.com/justintadlock/hybrid-base ... 

b) unzip and ftp to wp-content/themes and rename folder to hybrid-core

c) upload shoelace-theme-master to wp-content/themes and rename folder to shoelace

d) modify shoelace functions.php line 32 to this -> 
`
require_once( trailingslashit( get_template_directory() ) . 'hybrid-core/hybrid.php' );
`
essentially this is telling the shoelace theme to go up to the hybrid-core folder and even though there is not hybrid.php file, some how the magic occurs and voila ... theme shoelace = winner with bootstrap 3 and hybrid (or so it appears) ... 

and shoelace also seems to work nice out of the box with BuddyPress activity streams and groups ... haven't tested with bbPress but wow - gotta love good shoes with strong colorful laces - bravo!

**Comment by erikflowers** [comment]
I should have been more clear in the readme about this.

The theme is meant to be checked out as a Git repo, and the Library dir for hybrid-core is a sub-repo that is checked out as well.

As you have seen, you can't just download the zip and use it. I will go through the steps manually with Git through the command line and see if I can document how to get it all updated and working.

**Comment by chuckingit** [comment]
thank you :>)

**Comment by chuckingit** [comment]
Hi - this is just an update to my previous comment in that my success steps are / were wrong ... while i got it to work that way, the correct way is to download Hybrid Core and put everything in the Shoelace library folder and voila - works and no need to modify functions.php ... 

note i was confused between Hybrid Base and Hybrid Core ... and for anybody that might stumble on this thread, Hybrid Base is a starter theme that also needs to have the Hybrid Core files placed into the Hybrid Base library folder ... 

looping back to Shoelace ... once i installed Shoelace the correct way (vs my previous method above) i lost the nice formatting i saw before with BuddyPress and my primary menu is hidden  when logged in (the WordPress Multisite Menu covers it up), but suspect i will be able to address these via CSS tweaks in a child theme ... 

thank you Erik for sharing such a cool theme!

**Comment by erikflowers** [comment]
Can you expand on this?

Hybrid base is NOT a theme and its Library folder is a sub-repository to Hybrid Core. Hybrid Base is mean to be your OWN parent theme, and you just keep the Library (hybrid core) folder updated through the repository, either manually or by leaving it a git subrepo.

Can you post screenshots? Shoelace shouldn't really do anything to sites, all it is is blank, base WP loops in a starter layout using Bootstrap. Plugins shouldn't affect it unless it jumps in and messes with Hybrid provides for functions and such.

I want to keep Shoelace up to date and easy to use, so this information is valuable as I will be using it here at my work for an internal project and I want it as kosher as possible.

**Comment by chuckingit** [comment]
Hi Erik - happy to expand ... 

i had started thread at Theme Hybrid -> Hybrid Core and Shoelace theme for Bootstrap 3 integration and ... which is at this url -> http://themehybrid.com/support/topic/hybrid-core-and-shoelace-theme-for-bootstrap-3-integration-and ... in the event you cannot access that members only section, i created a pdf of that thread but since GitHub does not allow pdfs to be attached, i converted that pdf into these three jpgs:

![hybridcore-shoelace_page_1](https://cloud.githubusercontent.com/assets/4323987/2646530/8fdf1182-bf3f-11e3-90cf-7c4bc67009bd.jpg)
![hybridcore-shoelace_page_2](https://cloud.githubusercontent.com/assets/4323987/2646531/8fe1b432-bf3f-11e3-88f4-736308fea80d.jpg)
![hybridcore-shoelace_page_3](https://cloud.githubusercontent.com/assets/4323987/2646529/8fddee9c-bf3f-11e3-8dba-368ca6c62a3e.jpg)

essentially when i tried to activate the Hybrid Base theme, i got a wierd message (something about "cheet'n hugh") so the theme really didn't activate ... but once i followed Justin's advice and put the Hybrid Core files into the Hybrid Base library folder, then voila - Hybrid Base theme came alive ... 

here is some text of what Justin said to help me understand -> 

"Hybrid Base is just like any other theme that uses Hybrid Core. The only difference is that it's an example, "starter" theme for learning purposes. ....  Hybrid Base is the entire theme. Hybrid Core goes within Hybrid Base in its own folder. I typically use the library folder, but this can be named anything as long as you use the correct path when loading it. Since I personally use the library folder name, my code looks like this:
`require_once( trailingslashit( get_template_directory() ) . 'library/hybrid.php' );` .... hybrid-base or hybrid-base-master should be renamed to whatever the actual name of your theme is though."

with respect to my primary menu getting covered over by the WordPress Admin menu (when logged in) i created three other jpgs of screen shots ... 

here is site with Twenty 12 theme activated and you can see the primary menu is not covered up:
![cooltea org-screenshots03-twenty12b](https://cloud.githubusercontent.com/assets/4323987/2646710/f185dbf8-bf41-11e3-9091-24be50402dd5.jpg)

and here it is with Shoelace activated and you can see that the primary menu is barely visible (can't really see the menu items - "Connect - Learn - MyCoolTea - Other Networks - Shop") yet you can also see the same primary menu repeat at the bottom of the page (i only had one menu so i put it in both primary and secondary slots just to see how it looked):
![cooltea org-screenshots01-shoelace](https://cloud.githubusercontent.com/assets/4323987/2646599/8649b392-bf40-11e3-9a8e-eff34316f6c2.jpg)

and here is same site but in Twenty 13 theme and the primary menu is fine:
![cooltea org-screenshots02-twenty13](https://cloud.githubusercontent.com/assets/4323987/2646600/864f528e-bf40-11e3-85ff-1a95f9fc61d7.jpg)

now it is quite possible that this issue of primary nav bar getting covered over might be a Bootstrap 3 thing ... e.g., when i was creating this site -> http://avantigroup.com - using just Bootstrap 3, i found i had to add padding-top:70px to all my div ids in order to get those to not be covered by the fixed nav bar ... before i put together the Avanti site i had been testing responsive Big Picture template from http://html5up.net/ when i created this site, http://greatenergy.com, and somewhere along the way (between both sites) i had read other posts about using 70px padding ... 

i mention these other sites because in a previous thread with Justin, i had asked about creating one page sites and the consensus in that thread seemed to suggest not using WordPress (hammer) when all i needed was a screw driver (simple one page html5 template) ... so i had went off and used the Big Picture template but found hacking that to actually be a lot of work and i suspect my tweaks might have introduced bugs but it was good enough ... so then when i was putting together the Avanti site, i opted to go pure Bootstrap 3 only and while that worked, i found myself longing for some WordPress functionality (e.g., pop up images, form integration, ease of editing text) which got me to digging around web to see if there was theme that merged best of Bootstrap 3 with Hybrid and voila - your Shoelace theme ... 

looping back to folders ... i suspect that the best practice would be to have hybrid core installed in its own folder (e.g., wp-content/themes/hybrid-core) and then have Shoelace look for that folder instead of dumping hybrid core into a Shoelace library sub folder - in that if somebody had a Multisite install with several other themes referencing Hybrid Core, then that might save space ..??.. 

on other Bootstrap 3 fronts ... i did find some beautiful looking Bootstrap CSS but am currently at a loss as to how to make it work but mention in case you go "wow - that'd be a cool thing to incorporate with Shoelace" -> Bootflat – Flat UI Kit for Bootstrap CSS Framework -> at this url -> http://bootflat.github.io/

**Comment by erikflowers** [comment]
You have 2 issues here and they should be split out. One is about downloading the theme, and the other is about the CSS for the menu nav.

This issue has meandered a bit - but are you cloning the repository using Git, or downloading the Zip file? Downloading the Zip file is not supported by me and not recommended. 

Also, the hybrid-core files are included in the library folder as a git submodule so it can be updated via Github. Again - it's not meant to have hybrid-core downloaded somewhere else and then placed around.

If what you're doing works, that is fine, but that's not how I build it or intended it to be installed. Maybe it's too specific to my own needs, but you're going through a ton of extra steps when you don't need to.

Regarding the CSS issue, it is because the <nav> element is fixed to the top, and that other nav bar you show is as well. If you have 2 things that are fixed to the top at 0px, they will cover eachother. If you change the <nav>'s fixed distance of the top:0px, you can move it down wherever you want.

**Comment by chuckingit** [comment]
Thanks Erik for clarification ... with respect to using Git to clone ... i read your readme and think there could be one more step after the first line of get clone url and that is to make sure to change directory path into the new shoelace-theme folder, then run the git submodule init and update ... and indeed, hybrid-core library is there just as you designed ...

in looking back at this thread and comparing zip download vs git cloning, i think all you need to highlight zip option in readme is to tell people to download your theme, then download Hybrid Core as zip and move unzipped hybrid in your shoelace-theme library and voila ... but yes, i certainly get your point on ease of Git Cloning vs doing it via double zip downloads, unzips, move hyrbrid to correct library folder, etc ...  

Thanks again for your help and patience with this thread :)
